api_platform:
    title: '🚀 Boilerplate Symfony fast development'
    description: 'Boilerplate php 8.1 / symfony / fast development / hexagonal architecture (mix) and swoole ❤️'
    mapping:
        paths: ['%kernel.project_dir%/src']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    path_segment_name_generator: App\ThridParty\ApiPlatform\Core\SingularPathSegmentNameGenerator
    show_webby: false
