version: '3'

services:
    backend:
        build: ./
        ports:
            - '9091:9091'
        environment:
            DISABLE_DEFAULT_SERVER: 1 # Disable Swoole for dev
        entrypoint: php -S 0.0.0.0:9091 -t public
#        entrypoint: tail -f /dev/null
        volumes:
            - './:/app'

