name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run environment
        run: make app-run-fresh

      - name: Check tools && test
        run: make git-pre-commit-check
